### ISSUE TITLE
patch 生成

### ISSUE THREAD

**Issue by yangrudan** [mengning/mykernel#23]
`diff -Naur linux-5.4.34 linux-5.4.34-mykernel > mykernel-2.0_for_linux-5.3.34.patch`

请问 linux-5.4.34-mykernel这个文件夹怎么产生的呢？

**Comment by mengning** [comment]
这个命令是生成补丁包的命令，linux-5.4.34-mykernel是我开发mykernel时用的目录

**Comment by yangrudan** [comment]
> 这个命令是生成补丁包的命令，linux-5.4.34-mykernel是我开发mykernel时用的目录

请问您开发mykernel时用的目录（linux-5.4.34-mykernel）是您按照下面的命令打过补丁的目录吗？既有linux内核代码，也有您开发的代码，这样理解对吗。
```bash
cd linux-5.4.34
patch -p1 < ../mykernel-2.0_for_linux-5.4.34.patch
```

**Comment by mengning** [comment]
> > 这个命令是生成补丁包的命令，linux-5.4.34-mykernel是我开发mykernel时用的目录
> 
> 请问您开发mykernel时用的目录（linux-5.4.34-mykernel）是您按照下面的命令打过补丁的目录吗？既有linux内核代码，也有您开发的代码，这样理解对吗。
> 
> ```shell
> cd linux-5.4.34
> patch -p1 < ../mykernel-2.0_for_linux-5.4.34.patch
> ```

对的

**Comment by yangrudan** [comment]
> > > 这个命令是生成补丁包的命令，linux-5.4.34-mykernel是我开发mykernel时用的目录
> > 
> > 
> > 请问您开发mykernel时用的目录（linux-5.4.34-mykernel）是您按照下面的命令打过补丁的目录吗？既有linux内核代码，也有您开发的代码，这样理解对吗。
> > ```shell
> > cd linux-5.4.34
> > patch -p1 < ../mykernel-2.0_for_linux-5.4.34.patch
> > ```
> 
> 对的

谢谢~

**Comment by yangrudan** [comment]
已解决
