### ISSUE TITLE
执行到make的时候会出现报错

### ISSUE THREAD

**Issue by fx2003** [mengning/mykernel#8]
按照操作步骤到make的时候会报错找不到compiler-gcc5.h。
在https://git.kernel.org/pub/scm/linux/kernel/git/sashal/linux-stable.git/tree/include/linux/compiler-gcc5.h下载了一个也不行。
我的系统是Ubuntu 16.04 x64

**Comment by mengning** [comment]
我们以32位x86为实验环境的，需要安装32位的编译环境，包括头文件和一些静态库


建议到https://www.shiyanlou.com/courses/195 这里做实验，环境都被配好了


孟宁


在2017年04月19 16时11分, "fx2003"<notifications@github.com>写道:



按照操作步骤到make的时候会报错找不到compiler-gcc5.h。
在https://git.kernel.org/pub/scm/linux/kernel/git/sashal/linux-stable.git/tree/include/linux/compiler-gcc5.h下载了一个也不行。
我的系统是Ubuntu 16.04 x64

**Comment by XiaoZYang** [comment]
@fx2003 我遇到了一样的问题,因为gcc版本太高了,我的解决方法是`$ cd /path/to/linux-3.9.4/include/linux && ln -s compiler-gcc4.h compiler-gcc5.h `, 编译成功了,只是不知道会不会有别的问题.
